### PR TITLE
Fixed bug when documenting a constructor with generic arguments, the …

### PR DESCRIPTION
**Pull request by bjoernrennfanz**
…reflection xml was wrong. This results an ShowMissingComponent warning due not more matching XML files.

### CODE REVIEW

**Comment by EWSoftware** [comment]
Thanks for the fix

**Comment by EWSoftware** [comment]
I ended up reverting this change.  It seemed harmless enough but once I rebuilt MRefBuilder, the change broke most of the output for the generic classes in the test case project.  Can you supply an example that is not working with the original code?

**Comment by bjoernrennfanz** [comment]
Sure, the problem were an C++/CLI DLL with following Constructor like the following sample:
public TestClass(IEnumerable< KeyValuePair<String^, String^> >^ testFilter, StrategyEnum strategy);

Best regards

**Comment by EWSoftware** [comment]
The C++ compiler is well known for generating incorrect member IDs.  Try the [Member ID Fix-Ups Plug-In](http://ewsoftware.github.io/SHFB/html/17d977a6-e3dc-4ef4-9bbf-718ef4823854.htm) as it can correct most of the known C++ naming issues.  It also supports adding additional rules to correct new cases.

**Pull request merged**
