### PR TITLE
Spacing tweaks for block content

### PR DESCRIPTION
**Pull request by sharwell**
* Indent content of collapsible sections. This impact can be seen by comparing the alignment of the left edge of the main content on [this page (not indented)](http://ewsoftware.github.io/XMLCommentsGuide/html/81bf7ad3-45dc-452f-90d5-87ce2494a182.htm) with the content on [this page (indented)](http://tunnelvisionlabs.github.io/SHFB/docs-master/XMLCommentsGuide/html/81bf7ad3-45dc-452f-90d5-87ce2494a182.htm). Keep in mind this is closely related to #48 - if this change is applied without #48, some MAML content will receive two levels of indentation.
* Remove space between paragraphs in tables. This change significantly improves the ease of reading multi-line [conditions in exception tables](http://openstacknetsdk.org/docs-v2/html/M_OpenStack_Services_IHttpService_PrepareRequestAsyncFunc__1.htm).
* Slightly "tighten" the vertical spacing overall

### CODE REVIEW

**Comment by EWSoftware** [comment]
I'm okay with indenting the collapsible section content.  I don't like the other spacing changes.  The problem is that you are addressing one specific use that doesn't like right to you.  The problem is that anything with normal paragraphs get bunched up with no separation making it harder to read (content with actual paragraphs not "-or-" separators).  If you don't want paragraphs, use line breaks instead to get the desired spacing in those cases.

**Comment by sharwell** [comment]
Let me play with this one for a bit. The "vstudio" theme on MSDN used to use this spacing in exception tables, but they no longer do. The use of `<p>` elements for each line is commonplace. I'll update this pull request soon.

References:

[`List<T>.InsertRange`](https://msdn.microsoft.com/en-us/library/vstudio/884ee1fz.aspx)
[`List<T>.InsertRange` ("vstudio" theme)](https://msdn.microsoft.com/en-us/library/vstudio/884ee1fz.aspx)

**Comment by sharwell** [comment]
I updated this to restore spacing between paragraphs in a table. If you are still uncomfortable with this, just let me know and I'll split it into two pull requests (one for the collapsible sections and one for the paragraphs).

**Comment by EWSoftware** [comment]
I'll only merge the collapsible section change. I'm not interested in the paragraph spacing changes so there's no need for a separate pull request for them, they can just be reverted.

**Comment by sharwell** [comment]
Done :+1:

**Pull request merged**
