### PR TITLE
Improved code completion, especially in Visual Studio 2015

### PR DESCRIPTION
**Pull request by sharwell**
* Remove the `langword` prefix from custom completion items. I could not reproduce a crash in Visual Studio 2013 (standard or Roslyn preview), but these prefixes make it more difficult to enter these keywords efficiently. With the prefix removed, typing `true` and pressing Ctrl+Space is sufficient to trigger code completion in Visual Studio 2010 - 2013.
* Update `RoslynKeyboardFilter` to insert the completion characters (`/` and/or `>`) as necessary, to match the behavior of other documentation comment completion items in this environment.
* Update `AugmentedCompletionSet` to immediately commit on Ctrl+Space in Visual Studio 2015 when the result is unique and selected. This now matches the behavior for other completion items in the same list. This is necessary because the handling for immediate commit was relocated in Visual Studio 2015, and now only applies to items in the IntelliSense lists provided by Visual Studio's built-in IntelliSense services.

### CODE REVIEW

**Comment by EWSoftware** [comment]
I'm pretty sure the "langword" prefix is still required.  As I recall, the problem it works around occurs when you start typing a "&lt;<see" tag when the cursor is right at the start of an existing word.  While it may not occur in VS 2015 (pretty sure it still does but I can check), it does occur in VS 2010-2013 so it is still a required workaround.

**Comment by sharwell** [comment]
Thanks for the extra info. I tried to reproduce this, but did not test the specific case you describe. Since the overall usability of omitting the `langword` prefix is improved I'm hoping I can find another way to address the underlying problem.

**Comment by sharwell** [comment]
I wasn't able to reproduce this in Visual Studio 2010 or Visual Studio 2013. I did verify that the inclusion of `langword` in the prefix means you can't just type `true` and press <kbd>Ctrl</kbd>+<kbd>Space</kbd>, so this is a major productivity barrier. Can you look into the conditions/steps for reproducing this so hopefully I can find a solution that addresses both of our concerns? :+1:

**Comment by EWSoftware** [comment]
I ran into it several times while updating the comments in one of my projects.  I'll track down an example.

**Comment by EWSoftware** [comment]
Based on the code comment, this was only a problem in VS2013.  However, I can't seem to duplicate it now either.  It wasn't crashing in this code but rather on return utilizing the list of suggestions.  The only thing I found that fixed it was the addition of some extra text to the ID.

Looking back at the change history, I made this fix around the time Update 4 came out.  I was fairly late in applying that update, well after I'd made this fix, so there's a good change something in it corrected the underlying issue and is perhaps why it isn't happening any more.  As such, I'm going to go ahead and merge it.

If it gets reported again or I run into it and have to reapply the fix, the solution is probably to make the "langword" part a suffix rather than a prefix.  As I recall, it didn't care what text got added to workaround it.  I tested it with the text as a suffix and Ctrl+Space worked in that case so, if needed, it would still let you use it with the workaround in place.

**Pull request merged**
