### PR TITLE
Migrate to the MPFProj10 implementation from NuGet

### LINKED ISSUE #13: Consider using tunnelvisionlabs/MPFProj10
It's deployed as a NuGet package. It would make sense to move toward using that. However, when I had a quick look at the code a while ago it was missing a few bug fixes that I had in the SHFB copy (one in Utilities.cs related to recursive copies and one in FileNode.cs related to in-place renaming of a file that caused a problem with source control are the two I recall).  The code needs to be compared to see if anything else is missing and make them equivalent with regard to fixes.  Once done, the local copy of the MPFProj could go away in favor of the package.

### PR DESCRIPTION
**Pull request by sharwell**
This change does not implement all of the corrections described in the original code. However, it should be largely complete so I wanted to open the pull request to get discussion started. If the remaining issues are deemed minor enough, one possibility (but not the only possibility) is to incorporate this in roughly the current form, and then file issues on the MPFProj10 project for the remaining items to fix. Another possibility is to make this a long-running pull requests where we discuss the issues in advance of merging it down the road (the downside here being an increased chance of merge conflicts).

The primary advantage of this pull request is it offers a *tremendous* improvement to the **Show All Files** command performance.

Fixes #13

Notes to me:

* [ ] Implement "ReferenceOutputAssembly" in this project since MPFProj10 does not include built-in support for this property of a reference node.

### CODE REVIEW

**Comment by EWSoftware** [comment]
I'd rather see the two code bases compared and the missing issues fixed in MPFProj10 before using it in SHFB simply because I don't want to reintroduce the bugs that have been fixed.  Two fixes as noted in #13: one in Utilities.cs related to recursive copies and one in FileNode.cs related to in-place renaming of a file that caused a problem with source control).

I tagged all of my changes with my initials (EFW) so they're easy to find.

**Comment by sharwell** [comment]
That works for me. I'll update this pull request as I proceed.

**Comment by sharwell** [comment]
I think this should be closed in favor of #90.

**Comment by EWSoftware** [comment]
Closed in favor of #90.

**Pull request closed without merging**
