### PR TITLE
Fixed #477 - issue with negative enum values

### LINKED ISSUE #477: Enums with Negative Values fail in MRefBuilder
An enum such as the following that contains a negative value now fails with latest check-in:
```
    /// <summary>
    /// Defines the relative intensity (i.e., volume) of a musical line.
    /// </summary>
    public enum Dynamic
    {
        /// <summary>No dynamic is defined.</summary>
        Undefined = -1,
        /// <summary>pp - very soft.</summary>
        Pianissimo = 5,
        /// <summary>p - soft.</summary>
        Piano = 10,
        /// <summary>mp - half soft as <see cref="Piano"/>.</summary>
        MezzoPiano = 20,
        /// <summary>mf - half loud as <see cref="Forte"/>.</summary>
        /// <remarks>This is the default dynamic level.</remarks>
        MezzoForte = 40,
        /// <summary>f - loud.</summary>
        Forte = 80,
        /// <summary>ff - very loud.</summary>
        Fortissimo = 90
    }
```

Exception:
```
MRefBuilder : error :    at System.Convert.ToUInt64(Int32 value) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at System.Int32.System.IConvertible.ToUInt64(IFormatProvider provider) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at System.Convert.ToUInt64(Object value, IFormatProvider provider) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteLiteral(Literal literal, Boolean showType) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteExpression(Expression expression) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteAttributes(AttributeList attributes, SecurityAttributeList securityAttributes) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteMember(Member member, TypeNode type, Boolean includeSourceCodeContext) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteTypeElements(TypeNode type) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteType(TypeNode type) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitType(TypeNode type) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitTypes(TypeNodeList types) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespace(Namespace space) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespace(Namespace space) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespaces(NamespaceList spaces) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj]
Done Building Project &quot;D:\Projects\gsf\Build\Help\Working\GenerateRefInfo.proj&quot; (default targets) -- FAILED.
```

### PR DESCRIPTION
**Pull request by ritchiecarroll**
Latest check-in breaks negative enum values.

### CODE REVIEW

**Comment by ritchiecarroll** [comment]
Enums that contain negative values now fail with latest check-in (example below). This PR resolves.
```
    /// <summary>
    /// Defines the relative intensity (i.e., volume) of a musical line.
    /// </summary>
    public enum Dynamic
    {
        /// <summary>No dynamic is defined.</summary>
        Undefined = -1,
        /// <summary>pp - very soft.</summary>
        Pianissimo = 5,
        /// <summary>p - soft.</summary>
        Piano = 10,
        /// <summary>mp - half soft as <see cref="Piano"/>.</summary>
        MezzoPiano = 20,
        /// <summary>mf - half loud as <see cref="Forte"/>.</summary>
        /// <remarks>This is the default dynamic level.</remarks>
        MezzoForte = 40,
        /// <summary>f - loud.</summary>
        Forte = 80,
        /// <summary>ff - very loud.</summary>
        Fortissimo = 90
    }
```

**Comment by EWSoftware** [comment]
I think the `compare` variable also needs the unsigned long check at line 600 similar to the assignment for `fieldValue` just above it.

**Comment by ritchiecarroll** [comment]
Done. Nice catch.

**Comment by EWSoftware** [comment]
Thanks for the update.

**Pull request merged**
