### PR TITLE
Dynamic msbuild properties during VS build

### PR DESCRIPTION
**Pull request by ChristophLindemann**
Added support for _dynamic_ `msbuild` properties during Visual Studio build.
Previously, during VS build, properties set during `msbuild` targets where not available to the build task, when executed from VS. Here the project file was loaded, and only the static properties where available.

Now it is possible to implement custom targets which create/set properties, and make them available during SHFB tag substitution. (This previously only worked when executing `msbuild` directly, and not from solution build)

I use this to update the `HelpFileVersion` and some other text, and bind it against a specific git commit during build.

in the `.shfbproj` I can now add some custom targets:
```
<PropertyGroup>
    <BuildDependsOn>
      GetBuildGitVersion;
      $(BuildDependsOn)
    </BuildDependsOn>
  </PropertyGroup>

<Target Name="GetBuildGitVersion" Returns="$(BuildVersion)">

    <Message Importance="high" Text="running GetBuildGitVersion" />
    
    <Nerdbank.GitVersioning.Tasks.GetBuildVersion
      BuildingRef="$(_NBGV_BuildingRef)"
      BuildMetadata="@(BuildMetadata)"
      DefaultPublicRelease="$(PublicRelease)"
      GitRepoRoot="$(GitRepoRoot)">

      <Output TaskParameter="Version" PropertyName="BuildVersion" />
      <Output TaskParameter="AssemblyInformationalVersion" PropertyName="HelpInformationalVersion" />
      <Output TaskParameter="AssemblyFileVersion" PropertyName="HelpFileVersion" />
      <Output TaskParameter="SimpleVersion" PropertyName="BuildVersionSimple" />
      <Output TaskParameter="PrereleaseVersion" PropertyName="PrereleaseVersion" />
      <Output TaskParameter="MajorMinorVersion" PropertyName="MajorMinorVersion" />
      <Output TaskParameter="AssemblyVersion" PropertyName="AssemblyVersion" />
      <Output TaskParameter="GitCommitId" PropertyName="GitCommitId" />
      <Output TaskParameter="GitCommitIdShort" PropertyName="GitCommitIdShort" />
      <Output TaskParameter="GitVersionHeight" PropertyName="GitVersionHeight" />
      <Output TaskParameter="BuildNumber" PropertyName="BuildNumber" />
      <Output TaskParameter="BuildNumber" PropertyName="BuildVersionNumberComponent" />
      <Output TaskParameter="PublicRelease" PropertyName="PublicRelease" />
      <Output TaskParameter="CloudBuildNumber" PropertyName="CloudBuildNumber" Condition=" '$(CloudBuildNumber)' == '' "/>
      <Output TaskParameter="BuildMetadataFragment" PropertyName="SemVerBuildSuffix" />
      <Output TaskParameter="NuGetPackageVersion" PropertyName="NuGetPackageVersion" />
      <Output TaskParameter="NPMPackageVersion" PropertyName="NPMPackageVersion" />
      <Output TaskParameter="CloudBuildVersionVars" ItemName="CloudBuildVersionVars" />
    </Nerdbank.GitVersioning.Tasks.GetBuildVersion>

    <Warning Condition=" '$(HelpInformationalVersion)' == '' " Text="Unable to determine the git HEAD commit ID to use for informational version number." />
    <Message Condition=" '$(HelpInformationalVersion)' != '' " Text="Building version $(BuildVersion) from commit $(GitCommitId)"/>
    <Message Condition=" '$(HelpInformationalVersion)' == '' " Text="Building version $(BuildVersion)"/>
    <Message Text="HelpFileVersion: $(HelpFileVersion)" />
    <Message Text="HelpInformationalVersion: $(HelpInformationalVersion)" />

	<PropertyGroup>
		<SubstitutionTags>$(SubstitutionTags);HelpInformationalVersion=$(HelpInformationalVersion);HelpFileVersion=$(HelpFileVersion);Version=$(BuildVersion);GitCommitId=$(GitCommitId);</SubstitutionTags>
	</PropertyGroup>
  </Target>
```

### CODE REVIEW

**Comment by EWSoftware** [comment]
Thanks for the update

**Comment by chm-tm** [comment]
Note that this feature cannot currently be combined with the [Additional Reference Links Plug-In](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm), since the project is not built by means of the `BuildHelp` MSBuild task. I guess the same holds for the [Version Builder Plug-In](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm).

**Comment by chm-tm** [comment]
Note that this feature cannot be used when a property contains a semicolon in its value.

**Comment by ChristophLindemann** [comment]
> Note that this feature cannot be used when a property contains a semicolon in its value.

If you use semicolon, then you should make sure to properly escape the string.

You should use **`%3B`** for semicolon.

See: 
* [How to: Escape Special Characters in MSBuild](https://msdn.microsoft.com/en-us/library/ms228186.aspx)
* [MSBuild Special Characters](https://msdn.microsoft.com/en-us/library/bb383819.aspx)

**Comment by chm-tm** [comment]
Thanks for the suggestion.

Escaping semicolon with `%3B` may commonly work, but not so here. It seems that the `%3B` is unescaped before it gets to the code splitting the individual properties. The following authoring:
```XML
<Test2>Some Prop With %26lt%3B in it</Test2>
<Test3>Some Prop With %26lt in it</Test3>
<SubstitutionTags>Test1=$(Language);Test2=$(Test2);Test3=$(Test3);Test4=Some Prop With %26lt%3B in it</SubstitutionTags>
```
will output using `/v:d`:
```
Setting property Test1=en-US
Setting property Test2=Some Prop With &lt
Setting property Test3=Some Prop With &lt in it
Setting property Test4=Some Prop With &lt
```
```XML
<SubstitutionTags>Test=Bla0%3BBla1 Bla2=Bla3</SubstitutionTags
```
leads to the build error
```
The name "Bla1 Bla2" contains an invalid character " ".
```
These examples are boiled down from the real word example, when trying to substitute `NamespaceSummaries`.

**Comment by EWSoftware** [comment]
@chm-tm: It may be easier to use a [target override file](http://ewsoftware.github.io/SHFB/html/8ffc0d37-0215-4609-b6f8-dba53a6c5063.htm#TargetOverrides) to handle overriding the XML based properties.

**Pull request merged**
